var cricketers=
[	
	{	"Name":"Kohli",
		"FullName":"Virat Kohli",
		"country":"IND",
		"dummyPlayer":"Raina",
		"source":"images/Virat.jpg",
		"LastImgSource":"images/virat_t.png",
		"dummyPlayerStansSource":"images/LeftStansWithVirat.gif",
		"dummyPlayerRunSource":"images/LeftOneRunWithVirat.gif",
		"dummyPlayerOutSource":"images/LeftHandOUTWithVirat.gif",
		"answerImages":{	"startingPosition":"images/ViratStans.gif",
							"single":"images/ViratOne.gif",
							"twoRuns":"images/ViratTwo.gif",
							"four":"images/ViratFour.gif",
							"six":"images/ViratSix.gif",
							"out":"images/ViratOut.gif"
						}
	},
	{	"Name":"Dhoni",
		"FullName":"M S Dhoni",
		"country":"IND",
		"dummyPlayer":"Ashwin",
		"source":"images/Dhoni.jpg",
		"LastImgSource":"images/dhoni_t.png",
		"dummyPlayerStansSource":"images/LeftStansWithDhoni.gif",
		"dummyPlayerRunSource":"images/LeftOneRunWithDhoni.gif",
		"dummyPlayerOutSource":"images/LeftHandOUTWithDhoni.gif",
		"answerImages":{	"startingPosition":"images/DhoniStans.gif",
							"single":"images/DhoniOne.gif",
							"twoRuns":"images/DhoniTwo.gif",
							"four":"images/DhoniFour.gif",
							"six":"images/DhoniSix.gif",
							"out":"images/DhoniOut.gif"
						}
	},
	{	"Name":"Gayle",
		"FullName":"Chris Gayle",
		"country":"WI",
		"dummyPlayer":"Bravo",
		"source":"images/Gayle.jpg",
		"LastImgSource":"images/gayle_t.png",
		"dummyPlayerStansSource":"images/RightStansWithGayle.gif",
		"dummyPlayerRunSource":"images/RightHandOneRunWithGayle.gif",
		"dummyPlayerOutSource":"images/RightHandOUTWithGayle.gif",
		"answerImages":{	"startingPosition":"images/GayleStans.gif",
							"single":"images/GayleOne.gif",
							"twoRuns":"images/GayleTwo.gif",
							"four":"images/GayleFour.gif",
							"six":"images/GayleSix.gif",
							"out":"images/GayleOut.gif"
						}
	},
	{	"Name":"Sachin",
		"FullName":"Sachin Tendulkar",
		"country":"IND",
		"dummyPlayer":"Rohit",
		"source":"images/Sachin.jpg",
		"LastImgSource":"images/sachin_t.png",
		"dummyPlayerStansSource":"images/LeftStansWithSachin.gif",
		"dummyPlayerRunSource":"images/LeftHandOneRunWithSachin.gif",
		"dummyPlayerOutSource":"images/LeftHandOUTWithSachin.gif",
		"answerImages":{	"startingPosition":"images/SachinStans.gif",
							"single":"images/SachinOne.gif",
							"twoRuns":"images/SachinTwo.gif",
							"four":"images/SachinFour.gif",
							"six":"images/SachinSix.gif",
							"out":"images/SachinOut.gif"
						}
	},
	{	"Name":"Watson",
		"FullName":"Shane Watson",
		"country":"AUS",
		"dummyPlayer":"Maxwell",
		"source":"images/Shane.jpg",
		"LastImgSource":"images/watson_t.png",
		"dummyPlayerStansSource":"images/LeftStansWithWatson.gif",
		"dummyPlayerRunSource":"images/LeftOneRunWithWatson.gif",
		"dummyPlayerOutSource":"images/LeftHandOUTWithWatson.gif",
		"answerImages":{	"startingPosition":"images/WatsonStans.gif",
							"single":"images/WatsonOne.gif",
							"twoRuns":"images/WatsonTwo.gif",
							"four":"images/WatsonFour.gif",
							"six":"images/WatsonSix.gif",
							"out":"images/WatsonOut.gif"
						}
	}
]