var wlist = [  
  {
      "Lang": "Marathi",      
      "PrimaryWords": [
                        { "word": "टप", "words": ["ट","प"],"WordBank": ["टप", "टाप", "पाट", "टोप", "पोट", "टीप"] },
                        { "word": "बल", "words": ["ब", "ल"], "WordBank": ["बल", "बोल", "बेल", "लंब"] },
                        { "word": "कट", "words": ["क", "ट"], "WordBank": ["कट", "कटू", "कटी", "काटा", "काटे", "कोट", "कोटी", "काट", "कीट", "कूट", "टक", "टाक", "टाका", "टाकी", "टेक", "टेकू", "टीका"] },
                        { "word": "कड", "words": ["क", "ड"], "WordBank": ["कड", "कडा", "कडी", "कडू", "काडी", "कीड", "किडा", "कोडे", "डाक", "डिंक", "डूक", "डोके", "डाकू", "कंड", "डंका", "डाका"] },
                        { "word": "कर", "words": ["क", "र"], "WordBank": ["कर", "कार", "कोर", "कुर", "केर", "कोरी", "करा", "रोक", "रंक", "कैरी", "किरी"] },
                        { "word": "कप", "words": ["क", "प"], "WordBank": ["कप", "काप", "कूप", "केप", "कोप", "कंप", "पक", "पाक", "पीक", "पोक "] },
                        { "word": "पर", "words": ["प", "र"], "WordBank": ["पर", "पार", "परी", "पारा", "पीर", "पूर", "पेर", "पोर", "राप", "रूप", "रोप", "रीप", "रुपी", "रूपा"] },
                        { "word": "पत", "words": ["प", "त"], "WordBank": ["पत", "पात", "पीत", "पिता", "पती", "पूत", "पोत", "पंत", "तप", "ताप", "तापी", "तूप"] },
                        { "word": "पज", "words": ["प", "ज"], "WordBank": ["पूज", "पूजा", "पैज", "पुंजी", "पंजा", "जप", "जाप", "जीप"] },
                        { "word": "चक", "words": ["च", "क"], "WordBank": ["चक", "चाक", "चीक", "चूक", "चेक", "चौक", "चौकी", "कच", "काच", "कूच", "कैची", "कोच", "कंच", "काचा", "कोची"] },
                        { "word": "चप", "words": ["च", "प"], "WordBank": ["चाप", "चूप", "चेप", "चोप", "चंपा", "पाच", "पेच", "पोच", "पंच", "पंचा"] },
                        { "word": "चल", "words": ["च", "प"], "WordBank": ["चल", "चाल", "चूल", "चला", "चेला", "लाच", "लूच", "लेचा", "लिची"] },
                        { "word": "मज", "words": ["म", "ज"], "WordBank": ["मज", "माजी", "मोजा", "मांजा", "मजा", "माज", "जम", "जाम", "जोम", "जेम", "जीम"] },
                        { "word": "मर", "words": ["म", "र"], "WordBank": ["मर", "मार", "मीरा", "मिरी", "मारा", "मारी", "मेरी", "रमा", "राम", "रूम"] },
                        { "word": "मत", "words": ["म", "त"], "WordBank": ["मत", "मात", "माती", "मित", "तमा"] },
                        { "word": "खर", "words": ["ख", "र"], "WordBank": ["खरे", "खरी", "खार", "खारी", "खीर", "खूर", "खैर", "खोरे", "राख", "राखी", "रेख", "रेखा", "रोख"] },
                        { "word": "खल", "words": ["ख", "ल"], "WordBank": ["खल", "खाल", "खाली", "खोल", "खोली", "लख", "लाख", "लिख", "लेख", "खुले"] },
                        { "word": "रव", "words": ["र", "व"], "WordBank": ["रवा", "रवी", "राव", "रेवा", "रोवा", "वर", "वार", "वारी", "वारा", "वीर", "वैर"] },
                        { "word": "रन", "words": ["र", "न"], "WordBank": ["रान", "रीन", "नर", "नारी", "नारा", "नीर", "नूर"] },
                        { "word": "गर", "words": ["ग", "र"], "WordBank": ["गर", "गार", "गिरी", "गुरे", "गेरू", "गैर", "गोरे", "रग", "राग", "रंग", "रोग"] },
                        { "word": "गज", "words": ["ग", "ज"], "WordBank": ["गज", "गाज", "गाजे", "गुज", "गंज", "जग", "जाग", "जागी", "जोग", "जंग"] },
                        { "word": "बद", "words": ["ब", "द"], "WordBank": ["बाद", "बिंदू", "बुंदी", "बेदी", "बंद", "बंदी", "दाब", "दबा"] },
                        { "word": "बक", "words": ["ब", "क"], "WordBank": ["बक", "बाक", "बाकी", "बोका", "बाका"] },
                        { "word": "सप", "words": ["स", "प"], "WordBank": ["साप", "सूप", "सोप", "संप", "पास", "पसा", "पैसा", "पीस", "पूस", "पोस"] },
                        { "word": "सर", "words": ["स", "र"], "WordBank": ["सर", "सरा", "सूर", "सुरा", "सिर", "सौर", "सैर", "रस", "रास", "रेस", "रूस", "सार"] },
                        { "word": "सम", "words": ["स", "म"], "WordBank": ["सम", "साम", "सुम", "मासा", "सुमा", "मास", "सोम"] },
                        { "word": "घर", "words": ["घ", "र"], "WordBank": ["घर", "घार", "घेर", "घोर", "रीघ", "रेघ", "रेघा"] },
                        { "word": "वक", "words": ["व", "क"], "WordBank": ["वाक", "विक", "काव", "कवी", "कीव", "किंवा"] },
                        { "word": "जर", "words": ["ज", "र"], "WordBank": ["जर", "जार", "जारी", "जिरे", "जेर", "जरा", "राज", "राजा", "राजी", "राजू", "रोज", "रूज"] },
                        { "word": "दम", "words": ["द", "म"], "WordBank": ["दम", "दाम", "दमा", "मद", "मादी", "मूद", "मेद", "मंद", "मैदा", "मोद", ] },
                        { "word": "तर", "words": ["त", "र"], "WordBank": ["तर", "तार", "तारे", "तीर", "तोरा", "तरी", "तरा", "तूर", "तुरी", "रात", "रीत", "रुत", "रेत", "रती", "रेती", "रिती"] }
      ],
      "AllWords": [
                        { "lettertype": "primary", "letter": "क", "letterpoint": 3 },
                        { "lettertype": "primary", "letter": "त", "letterpoint": 3 },
                        { "lettertype": "primary", "letter": "च", "letterpoint": 3 },
                        { "lettertype": "primary", "letter": "न", "letterpoint": 3 },
                        { "lettertype": "primary", "letter": "प", "letterpoint": 3 },
                        { "lettertype": "primary", "letter": "स", "letterpoint": 3 },
                        { "lettertype": "primary", "letter": "द", "letterpoint": 3 },
                        { "lettertype": "primary", "letter": "ग", "letterpoint": 3 },
                        { "lettertype": "primary", "letter": "ल", "letterpoint": 3 },
                        { "lettertype": "primary", "letter": "ब", "letterpoint": 3 },
                        { "lettertype": "primary", "letter": "म", "letterpoint": 3 },
                        { "lettertype": "primary", "letter": "अ", "letterpoint": 3 },
                        { "lettertype": "primary", "letter": "ज", "letterpoint": 5 },
                        { "lettertype": "primary", "letter": "व", "letterpoint": 5 },
                        { "lettertype": "primary", "letter": "य", "letterpoint": 5 },
                        { "lettertype": "primary", "letter": "ड", "letterpoint": 5 },
                        { "lettertype": "primary", "letter": "ह", "letterpoint": 5 },
                        { "lettertype": "primary", "letter": "छ", "letterpoint": 5 },
                        { "lettertype": "primary", "letter": "ध", "letterpoint": 5 },
                        { "lettertype": "primary", "letter": "ख", "letterpoint": 7 },
                        { "lettertype": "primary", "letter": "थ", "letterpoint": 7 },
                        { "lettertype": "primary", "letter": "र", "letterpoint": 7 },
                        { "lettertype": "primary", "letter": "भ", "letterpoint": 7 },
                        { "lettertype": "primary", "letter": "श", "letterpoint": 7 },
                        { "lettertype": "primary", "letter": "फ", "letterpoint": 7 },
                        { "lettertype": "primary", "letter": "घ", "letterpoint": 7 },
                        { "lettertype": "primary", "letter": "झ", "letterpoint": 7 },
                        { "lettertype": "primary", "letter": "ए", "letterpoint": 7 },
                        { "lettertype": "primary", "letter": "ई", "letterpoint": 7 },
                        { "lettertype": "primary", "letter": "ट", "letterpoint": 9 },
                        { "lettertype": "primary", "letter": "ण", "letterpoint": 9 },
                        { "lettertype": "primary", "letter": "ऐ", "letterpoint": 9 },
                        { "lettertype": "primary", "letter": "ऊ", "letterpoint": 9 },
                        { "lettertype": "primary", "letter": "ठ", "letterpoint": 11 },
                        { "lettertype": "primary", "letter": "ढ", "letterpoint": 11 },
                        { "lettertype": "primary", "letter": "क्ष", "letterpoint": 11 },
                        { "lettertype": "primary", "letter": "ळ", "letterpoint": 11 },
                        { "lettertype": "primary", "letter": "ष", "letterpoint": 11 },
                        { "lettertype": "primary", "letter": "ज्ञ", "letterpoint": 11 },
                        { "lettertype": "matra", "letter": "ा", "letterpoint": 1 },
                        { "lettertype": "matra", "letter": "ि", "letterpoint": 3 },
                        { "lettertype": "matra", "letter": "ी", "letterpoint": 3 },
                        { "lettertype": "matra", "letter": "ु", "letterpoint": 3 },
                        { "lettertype": "matra", "letter": "ू", "letterpoint": 3 },
                        { "lettertype": "matra", "letter": "े", "letterpoint": 3 },
                        { "lettertype": "matra", "letter": "ै", "letterpoint": 5 },
                        { "lettertype": "matra", "letter": "ो", "letterpoint": 3 },
                        { "lettertype": "matra", "letter": "ौ", "letterpoint": 7 },
                        { "lettertype": "matra", "letter": "ं", "letterpoint": 5 },
                        { "lettertype": "matra", "letter": "ः", "letterpoint": 9 }
                ],

      "UkarWords": ["ा","ि","ी","ु","ू","े","ै","ो","ौ","ं","ः"],
      "BasicWord": ["क", "त", "च", "न", "प", "स", "द", "ग", "ल", "ब", "म", "अ", "ज", "व", "य", "ड", "ह", "छ", "ध", "ख", "थ", "र", "भ", "श", "फ", "घ", "झ", "ए", "ई", "ट", "ण", "ऐ", "ऊ", "ठ", "ढ", "क्ष", "ळ", "ष", "ज्ञ"],
           

      "Primary11Words": ["अ", "आ", "इ", "ई", "उ", "ऊ", "ऋ", "ए", "ऐ", "ओ", "औ", "अं", "अः", "क", "ख", "ग", "घ", "ङ", "च", "छ", "ज", "झ", "ञ", "ट", "ठ", "ड", "ढ", "ण", "त", "थ", "द", "ध", "न", "प", "फ", "ब", "भ", "म", "य", "र", "ल", "व", "श", "ष", "स", "ह", "ळ", "क्ष", "ज्ञ", "ा", "ि", "ी", "ो", "ौ", "ः", "ु", "ू", "े", "ै", "ं"],
  }
];